### ISSUE TITLE
Environment File Flag

### ISSUE THREAD

**Issue by gg-chrisd** [okta/okta-aws-cli#108]
Is it possible to get a flag to specify the `.env` file's location or an environment variable or just a location that it will always check similar to gimme-aws-creds `.okta_aws_login_config` file (that would be preferred)?

Otherwise, we can only run the command from the same directory as the `.env` file is located or have to specify a large number of flags.

**Comment by lw-cchapin** [comment]
@gg-chrisd Did you find a solution for this?

**Comment by gg-chrisd** [comment]
The solution we use is just to create a file (we name it `.okta_aws_cli_config`) containing all the environment variables we want and then source that file in the `.zshrc` or `.bashrc` file depending on what your guys are using.

An example config file:

```
export OKTA_AWSCLI_ORG_DOMAIN={your domain}
export OKTA_AWSCLI_OIDC_CLIENT_ID={your id}
export OKTA_AWSCLI_SESSION_DURATION=14400
export OKTA_AWSCLI_FORMAT=aws-credentials
export OKTA_AWSCLI_OPEN_BROWSER=true
export OKTA_AWSCLI_CACHE_ACCESS_TOKEN=true
export OKTA_AWSCLI_WRITE_AWS_CREDENTIALS=true

alias awsaccount1="okta-aws-cli web -p {aws_profile_name} -a {app_id}"
alias awsaccount2, etc etc.
```

Then just add `source ~/.okta_aws_cli_config` to your `~/.zshrc` file or whatever shell config you use.

**Comment by lw-cchapin** [comment]
Thank you
