### ISSUE TITLE
OKTA_AWSCLI_PROFILE env var ignored

### ISSUE THREAD

**Issue by josephlbarnett** [okta/okta-aws-cli#109]
I can use `--profile <profile_name>` to have okta-aws-cli write creds to a given profile in ~/.aws/credentials, but if I set the same value in a `OKTA_AWSCLI_PROFILE` env variable per the README.md, it writes to the `default` profile instead

**Comment by monde** [comment]
fix released in https://github.com/okta/okta-aws-cli/releases/tag/v1.0.2
