### ISSUE TITLE
What is the purpose of adding the OIDC Native application client id to use for Okta AWS CLI in Okta Identity Engine

### ISSUE THREAD

**Issue by rghankota** [okta/okta-aws-cli#116]
Is there any reason behind adding the OIDC Native application Client ID to use for Okta AWS CLI? why did it made mandatory?

**Comment by monde** [comment]
hey @rghankota , the OIDC Native application is the entry into this flow and is paired with an AWS Fed App. The OIDC Native app gives access to your users, and the AWS Fed App is used for direct communication that takes place between AWS and Okta to establish your trust to access AWS resources.

**Comment by rghankota** [comment]
Thanks Monde.
