### ISSUE TITLE
Improve UX around invalid cached token

### ISSUE THREAD

**Issue by michaeldop** [okta/okta-aws-cli#118]
If I have an access token cached, but it is invalid due to me logging out of my session I get this error (whether I use the the --cache-access-token flag or not)

```
Error: fetching SSO web token received API response "400 Bad Request", error: "invalid_grant", description: "The 'subject_token' either expired or the session associated with it was terminated."
```

The only way to get around this issue that I have found is to delete the cached token
```
rm -rf ~/.okta/awscli-access-token.json
```

Would it be possible to catch this error and continue on with the login flow and/or remove the cached token?

**Comment by lw-cchapin** [comment]
#114

**Comment by monde** [comment]
@michaeldop , agreed, that would be better behavior in the cached token flow. I'll see what I can do.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-643512
