### ISSUE TITLE
Enable Private/Incognito Window for "--open-browser" flag

### ISSUE THREAD

**Issue by ganderaj** [okta/okta-aws-cli#131]
Team,

Due to our Organizational standards, we are being forced to copy the URL for Device Activation and open it in an incognito window to activate our session.

Use of flag "--open-browser" is not of great help as the regular browser window does not support OKTA login for our elevated accounts (AWS access). Hence we need to open the URL on a private window which I go through at least 40times a day.

I request concerned to kindly consider it as a feature request to provide support for launching Device Activation URLs on Private/Incognito Window. Or, you may guide me to the file which needs an update to enable this feature and I'll do it on my installation.

Thank you in advance.

**Comment by monde** [comment]
Interesting. We are just using the golang browser package https://github.com/pkg/browser to open the browser. I'm on OSX and I can see they are just using the OSX `open` command w/ one argument - the URL https://github.com/pkg/browser/blob/master/browser_darwin.go

However, I've found you can use open on OSX to launch chrome with the incognito arg: `open -na "Google Chrome" --args -incognito https://google.com/` . I'd need to submit a PR to that project, and most likely, it's only google chrome specific.
