### ISSUE TITLE
Add 'exec' subcommand to avoid writing credentials to disk or injecting into the shell

### ISSUE THREAD

**Issue by jeffreymlewis** [okta/okta-aws-cli#135]
Add an `exec` flag or subcommand, allowing the execution of commands like 'terraform' without writing credentials to disk and without injecting credentials into the shell. (Both [aws-vault](https://github.com/99designs/aws-vault) and [saml2aws](https://github.com/Versent/saml2aws) implement a similar feature.)

Example syntax:

```shell
okta-aws-cli exec -- terraform apply
```

**Comment by monde** [comment]
I'll see if I can get this in on the headless feature work I'm doing atm.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-653000

**Comment by manchicken** [comment]
```sh
#!/usr/bin/env bash

OUTPUT=$(okta-aws-cli  -o $OKTA_HOST --oidc-client-id $OKTA_OIDC_ID -b)

# Validate the output, just to be safe...
PASSFAIL=$(perl -e 'if ($ARGV[0] =~ /\A(export\s+?AWS_(ACCESS_KEY_ID|SECRET_ACCESS_KEY|SESSION_TOKEN)=[a-zA-Z0-9=+\/]+\n){2}(export\s+?AWS_(ACCESS_KEY_ID|SECRET_ACCESS_KEY|SESSION_TOKEN)=[a-zA-Z0-9=+\/]+)\Z/) { print "PASS" } else { print "FAIL" }' "$OUTPUT")

if [ "$PASSFAIL" != "PASS" ]; then
  echo "ERROR: Unexpected output from okta-aws-cli"
  echo "Output was:"
  echo "$OUTPUT"
else
  eval "$OUTPUT"
  echo "AWS credentials set from Okta"
fi
```

I whipped this up for personal use.

1Password does something similar to what this issue describes in their CLI, and I love it: https://developer.1password.com/docs/cli/secret-references/#use-with-environment-files
