### ISSUE TITLE
Non-standard configuration file location

### ISSUE THREAD

**Issue by smlx** [okta/okta-aws-cli#136]
`~/.okta/` is a non-standard location for configuration files. It would be nice if this tool could use `$XDG_CONFIG_HOME` (as per [XDG Spec.](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) on Linux),  `~/Library/Application Support/<app-identifier>` (as per [Apple guidelines](https://developer.apple.com/library/archive/documentation/General/Conceptual/MOSXAppProgrammingGuide/AppRuntime/AppRuntime.html) on macOS) etc. There's a nice library for this [here](https://github.com/adrg/xdg).

**Comment by monde** [comment]
I'm going to close this request out - our open source tools, like our SDKs, standardized on having a config at `$HOME/.okta/okta.yaml`.
