### ISSUE TITLE
Consider removing these WARNING logs

### ISSUE THREAD

**Issue by michaeldop** [okta/okta-aws-cli#142]
Since you have to explicitly ask for these items by passing in cli args, `-x` or `-l`, do we need to also have the WARNING log?

https://github.com/okta/okta-aws-cli/blob/master/internal/output/aws_credentials_file.go#L159-L164

**Comment by monde** [comment]
I got this into the v2 beta work https://github.com/okta/okta-aws-cli/releases/tag/v2.0.0-beta.1
