### ISSUE TITLE
Remove version number from binary

### ISSUE THREAD

**Issue by mieliespoor** [okta/okta-aws-cli#154]
The release binaries for this cli have the version number in the name of the binary. Can this be removed and use standard conventions where the binary name is consistent through versions. 

See: https://github.com/okta/okta-aws-cli/blob/master/.goreleaser.yaml#L18

The fix here is to change it to:

```
binary: '{{ .ProjectName }}'
```

The problem here is that when you deploy this, you also need to rename the binary as you cannot then simply call `okta-aws-cli` as the documentation state without renaming the binary.

I'm happy to make this pull request myself.

**Comment by monde** [comment]
I can make it so.
