### ISSUE TITLE
--profile flag does not take precedence over OKTA_AWSCLI_PROFILE environment variable

### ISSUE THREAD

**Issue by emacdona** [okta/okta-aws-cli#157]
![image](https://github.com/okta/okta-aws-cli/assets/234140/2c8c4580-b229-4073-8be1-d0fc30a31ad5)

**Comment by monde** [comment]
Hi @emacdona I believe [v1.2.2](https://github.com/okta/okta-aws-cli/releases/tag/v1.2.2) fixed [this bug](https://github.com/okta/okta-aws-cli/pull/124). Also, we just released v2.0.0.
