### ISSUE TITLE
Choosing IdP and Role directly upon okta-aws-cli execution without having to select it interactively

### ISSUE THREAD

**Issue by kduvzc** [okta/okta-aws-cli#158]
I'd like to be able to execute a shell script that would simply run okta-aws-cli to authenticate me in a non-interactive way for some batch-mode operations. Ideally I would like to avoid the browser pop-up and having to select IdP and Role interactively from the terminal. This is something that was possible with gimme-aws-creds. Is there any way to replicate this behaviour?

**Comment by quixand** [comment]
this may go some way to providing this functionality https://github.com/okta/okta-aws-cli/pull/162

**Comment by kduvzc** [comment]
#162 seems to be more about support for multiple AWS profiles. I don't see how that could allow execution in batch mode to avoid having to perform the following without user interaction:

- Browser pop-up response
- Choose an IdP
- Choose a Role

**Comment by monde** [comment]
Preselect IdP and Role ARNs w/ `--aws-iam-role ` and `--aws-iam-idp`

https://github.com/okta/okta-aws-cli?tab=readme-ov-file#global-settings

**Comment by kduvzc** [comment]
@monde ... thanks for pointing out those command line flags. However, those still can't avoid the browser pop-up window, right?

**Comment by Shane-OH** [comment]
@monde As the user above mentioned using those arguments still opens to browser prompt, Is there any way to disable it?

**Comment by monde** [comment]
https://github.com/okta/okta-aws-cli/pull/172
https://github.com/okta/okta-aws-cli/issues/168

**Comment by kduvzc** [comment]
I've tested the merged fix by building the latest master branch and I no longer get the browser pop-up when omitting the `--open-browser` flag. However, the command just hangs at the following prompt:
```
Open the following URL to begin Okta device authorization for the AWS CLI

https://vzc.okta.com/activate?user_code=<one_time_code>
```
It is basically waiting for me to click on the link to press the NEXT button below:

<img width="398" alt="image" src="https://github.com/okta/okta-aws-cli/assets/60737470/9c308503-aa70-4674-8688-aa891463066c">

Is it possible to simply avoid having to go through browser confirmation at all?

**Comment by monde** [comment]
@kduvzc the human has to prove themselves with the web browser. However, `okta-aws-cli` has a flag `--cache-access-token` that will persist the access token that is fetched from the browser interaction. That access token is good for one hour and will not cause the web browser to be popped again on subsequent commands.

```
# first time this will pop the web browser
$ okta-aws-cli web --oidc-client-id 0oabc --org-domain test.oktacom --open-browser --cache-access-token

# given a successful authorization this will not pop the web browser for the next hour
$ okta-aws-cli web --oidc-client-id 0oabc --org-domain test.oktacom --open-browser --cache-access-token
```
