### ISSUE TITLE
--open-browser randomly uses Safari

### ISSUE THREAD

**Issue by wicol** [okta/okta-aws-cli#159]
I use Chrome as my system web browser. Yet half of the time `--open-browser` opens Safari - where I'm not logged in. So I have to copy paste the URL to Chrome and authenticate there.

Is this a bug in the browser package..? My colleagues are experiencing the same bug so it's not just me (but could be caused by company software..? who knows.). Would you consider bumping the version of the browser lib, or even implementing something for customising the browser opening as requested in other issues?

**Comment by monde** [comment]
okta-aws-cli uses the golang browser package/library. For OSX it just forks out to the `open` command https://github.com/pkg/browser/blob/master/browser_darwin.go#L4
If you go to the command line and do a `open https://www.okta.com/` and it opens with Safari then this is related to your MacBook settings https://support.apple.com/en-us/102362#:~:text=versions%20of%20macOS-,From%20the%20Apple%20menu%20%EF%A3%BF%20in%20the%20corner%20of%20your,%E2%80%9CDefault%20web%20browser%E2%80%9D%20menu.

**Comment by wicol** [comment]
I've double checked my system browser setting. The issue is that that's not respected. I'll try to run `open` lots of times over time and see if it behaves the same way.

**Comment by wicol** [comment]
Oh rly, I saw the discussions around that but didn't realize it was implemented. I'll try it out!

**Comment by monde** [comment]
Closing this one, v2 has [customizable open browser command](https://github.com/okta/okta-aws-cli?tab=readme-ov-file#alternative-open-browser-command):

#### OSX / MacBook
```
# OSX examples, the device authorization URL is appended to the browser args.

$ okta-aws-cli web \
  --oidc-client-id abc \
  --org-domain test.okta.com \
  --open-browser-command "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --profile-directory=\"Profile\ 1\""

$ okta-aws-cli web \
  --oidc-client-id abc \
  --org-domain test.okta.com \
  --open-browser-command "open -na \"Google\ Chrome\" --args --incognito"
```

#### Windows

```
REM Windows examples, the device authorization URL is appended to the browser
REM args using cmd.exe with the run command flag /C used to spawn the browser
REM that is installed on the host OS e.g. medge, chrome, firefox . Additional
REM arguments can be passed on to the browser command that are valid for it.

> okta-aws-cli web \
  --oidc-client-id abc \
  --org-domain test.okta.com \
  --open-browser-command "cmd.exe /C start msedge"

> okta-aws-cli web \
  --oidc-client-id abc \
  --org-domain test.okta.com \
  --open-browser-command "cmd.exe /C start chrome"

> okta-aws-cli web \
  --oidc-client-id abc \
  --org-domain test.okta.com \
  --open-browser-command "cmd.exe /C start chrome --incognito"

> okta-aws-cli web \
  --oidc-client-id abc \
  --org-domain test.okta.com \
  --open-browser-command "cmd.exe /C start chrome --profile-directory=\"Profile\ 1\""
```
