### ISSUE TITLE
add option to add region to AWS Profile

### ISSUE THREAD

**Issue by igaskin** [okta/okta-aws-cli#160]
when running `okta-aws-cli` with the `---profile` and `--write-aws-credentials` options, the out data does not include a `region`.   This will result in the following error if no region is specified.

```
a region was not specified. You can run 'aws configure' or choose a profile with a region
```

The scope of this request is to add an option to include a `region` to write to the aws profile.

_update file writing_
https://github.com/okta/okta-aws-cli/blob/master/internal/output/aws_credentials_file.go#L208

**Comment by monde** [comment]
addressed in https://github.com/okta/okta-aws-cli/releases/tag/v2.1.0
