### ISSUE TITLE
2.0.0 release still shows "-beta.6" in version output

### ISSUE THREAD

**Issue by joshgch** [okta/okta-aws-cli#164]
When you run `okta-aws-cli --version` the output still shows `okta-aws-cli version 2.0.0-beta.6` despite this being GA. 

This is also shown in the UserAgent: `okta-aws-cli/2.0.0-beta.6 (go1.21.6; darwin; arm64)`

https://github.com/okta/okta-aws-cli/blob/master/internal/config/config.go#L42

**Comment by timharris777** [comment]
I can confirm this

**Comment by monde** [comment]
facepalm!

**Comment by joshgch** [comment]
@monde please push v2.0.1 to homebrew, it is still showing the old version.
