### ISSUE TITLE
okta-aws-cli_v2.0.0.exe being flagged by AV

### ISSUE THREAD

**Issue by grahamfw-cfa** [okta/okta-aws-cli#166]
The latest Windows version (okta-aws-cli_v2.0.0.exe) is being tagged by Windows Defender as well as a few others according to VirusTotal.

VirusTotal link: https://www.virustotal.com/gui/file/8a1d71fa628f1f081f43ff72bca3b8a8fa078cb4d52e094426b3f56f9a54a57d/detection

**Comment by monde** [comment]
We are getting registered on Chocolatey and they are telling us golang built binaries for Windows amd64 are trigging AVs, it's not just us. We are going to address this in the short term by only releasing the i386 Windows version. It is unacceptable to have the binaries we produce triggering as virus infected.

@jefftaylor-okta

**Comment by joshgch** [comment]
@monde please push v2.0.1 to homebrew. It isn't available there yet.

**Comment by minhio** [comment]
any ideas on when windows amd64 binaries will available again? (or if there are any workaround?) thanks!

**Comment by monde** [comment]
hi @minhio I'm not sure when we'll look at publishing a 64 bit version again. As i386 binary will run on amd64 we'd rather just publish that binary and not have false positive AV results causing doubt. Even though it is well known that many binaries built with golang for amd64 will trigger AV false positives.
