### ISSUE TITLE
MacOS notarization

### ISSUE THREAD

**Issue by exitcode0** [okta/okta-aws-cli#17]
Not 100% sure that notarization is the correct term here, that said:
downloading the okta-aws-cli binary on macos and attempting to execute will result in a error
`okta-aws-cli_v0.0.4” can’t be opened because Apple cannot check it for malicious software.`

This can be overidden in Security & Privacy in System Preferences but this is not ideal for a widespread deployment
Perhaps a brew.sh package could be investigated?

**Comment by monde** [comment]
Thanks for pointing this out @exitcode0 . It fell off my todo list and we are going to fix this for GA. We are still calling this a beta release.

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-545155

**Comment by monde** [comment]
@exitcode0 We just released v0.1.0 our GA release https://github.com/okta/okta-aws-cli/releases/tag/v0.1.0
OSX bins signed with Okta's Apple certificate are now part of our releases. Also be sure to double check the read me, the UX has improved with regards to multiple AWS Fed Apps.
Thanks!

**Comment by andrew-kline** [comment]
Hi @monde, utilizing the okta-aws-cli_0.1.0_Darwin_x86_64_signed release still results in the failed check for me. Running Monterey 12.6.2

**Comment by monde** [comment]
@andrew-kline are you refering to the initial warning when you run the binary the first time on mac?
<img width="447" alt="image" src="https://user-images.githubusercontent.com/201/210644684-7cddbda4-ab3b-4d5e-a6ae-2e36783853e7.png">

Using `codesign` you can see that the `okta-aws-cli_v0.1.0` binary in `okta-aws-cli_0.1.0_Darwin_x86_64_signed` is notarized
```
codesign -dv --verbose okta-aws-cli_v0.1.0
Executable=/Users/mikemondragon/Downloads/okta-aws-cli_0.1.0_Darwin_x86_64_signed/okta-aws-cli_v0.1.0
Identifier=okta-aws-cli_v0
Format=Mach-O thin (x86_64)
CodeDirectory v=20500 size=110747 flags=0x10000(runtime) hashes=3455+2 location=embedded
Signature size=9051
Authority=Developer ID Application: Okta, Inc. (B7F62B65BN)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Dec 22, 2022 at 1:01:02 PM
Info.plist=not bound
TeamIdentifier=B7F62B65BN
Runtime Version=10.9.0
Sealed Resources=none
Internal requirements count=1 size=176
```

And for the unsigned version in `okta-aws-cli_0.1.0_Darwin_x86_64`, `codesign` indicates that binary is not singed:
```
codesign -dv --verbose okta-aws-cli_v0.1.0
okta-aws-cli_v0.1.0: code object is not signed at all
```

**Comment by andrew-kline** [comment]
No, the same error as exitcode0:
![image](https://user-images.githubusercontent.com/65789862/210656128-9a5cfe97-66be-4522-949e-dd768d365ccb.png)

The binary does indicate that it is signed, which is interesting:
`akline$ codesign -dv --verbose okta-aws-cli_v0.1.0 
Executable=/Users/akline/Downloads/okta-aws-cli_0.1.0_Darwin_x86_64_signed/okta-aws-cli_v0.1.0
Identifier=okta-aws-cli_v0
Format=Mach-O thin (x86_64)
CodeDirectory v=20500 size=110747 flags=0x10000(runtime) hashes=3455+2 location=embedded
Signature size=9051
Authority=Developer ID Application: Okta, Inc. (B7F62B65BN)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Dec 22, 2022 at 1:01:02 PM
Info.plist=not bound
TeamIdentifier=B7F62B65BN
Runtime Version=10.9.0
Sealed Resources=none
Internal requirements count=1 size=176`

Is there potentially a system setting that would inhibit macos from identifying that it is signed?

**Comment by monde** [comment]
Thanks for those details @andrew-kline -- I'm going to link up with our release engineer that is the Apple expert. I'll report back.

**Comment by andrew-kline** [comment]
Interesting, it works when unpacking via the `tar -xvf` utility, but if you unpack it using the macos native unpacking (after downloading from Chrome), it does not recognize that it is signed.

**Comment by rlepage-okta** [comment]
@andrew-kline forgive me for asking, but is it possible you have a non-Apple unpacker that ***might*** have interfered with the normal unpacking of the `tar.gz` archive?

Just so I can remove that possibility from the investigation.

**Comment by rlepage-okta** [comment]
@andrew-kline one additional thing, *just* to be sure: was the machine that displayed that issue connected to the Internet in any way? If it wasn't, it ***might*** be GateKeeper acting up.

**Comment by rlepage-okta** [comment]
@andrew-kline circling back one more time, as I'm still looking at clarifying this.

Can you open your `System Preferences`, go into `Security & Privacy`, and tell me what is `Allow apps downloaded from` set to? In your case, it might be set to `App Store` only.

**Comment by monde** [comment]
Ok, I discovered some more details on [v0.2.0](https://github.com/okta/okta-aws-cli/releases/tag/v0.2.0). Check it out @andrew-kline 

Somehow, downloading the signed tar.gz with Chrome messing with the trust chain on OSX.
I was able to get trust in this fasion:

1. curl down the archive
2. in the shell open finder `open .` on the PWD
3. click on tar.gz in Finder, letting OSX unarchive the thing
4. cd into the named directory OSX unarchive makes `cd okta-aws-cli_0.2.0_Darwin_x86_64_signed`
5. profit
```
$ ./okta-aws-cli_v0.2.0 --version
okta-aws-cli version 0.2.0
```

This is what codesign says about the binary
```
codesign -dv --verbose okta-aws-cli_v0.2.0
Executable=/private/tmp/v0.2.0/okta-aws-cli_v0.2.0
Identifier=okta-aws-cli_v0
Format=Mach-O thin (x86_64)
CodeDirectory v=20400 size=110835 flags=0x0(none) hashes=3458+2 location=embedded
Signature size=9051
Authority=Developer ID Application: Okta, Inc. (B7F62B65BN)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Jan 24, 2023 at 11:36:25 AM
Info.plist=not bound
TeamIdentifier=B7F62B65BN
Sealed Resources=none
Internal requirements count=1 size=176
```

**Comment by alexoughton** [comment]
I experienced exactly the same problem with my own CLI tools on Mac. Nothing I tried with .tgz files or .zip files would be recognized as properly signed after downloading via a web browser.

The solution I found was to use a .pkg installation package:

1. Build and sign the binary itself
2. Create a .pkg installation package. Sign that too.
3. Notarize the signed package file.

Until this is resolved, another workaround is to open the binary by right-clicking it, and selecting "open with > terminal". Mac OS will then display a prompt which allows you to accept the risk, rather than just refusing to run. Future executions will just work without a prompt.

**Comment by kevincantu** [comment]
The "signed" build of `okta-aws-cli_0.2.1_Darwin_x86_64_signed.tar.gz` I downloaded from you for v0.2.1 ([releases](https://github.com/okta/okta-aws-cli/releases/tag/v0.2.1)) is.. not signed:
<img width="283" alt="Screen Shot 2023-03-02 at 6 28 11 PM" src="https://user-images.githubusercontent.com/27978219/222616781-b729e48f-34d7-4b20-a378-dd75ddf56dc5.png">

**Comment by monde** [comment]
Let me guess @kevincantu , you used the system archiver out of Chrome to open the download? Take the time to read all the comments on this issue.

**Comment by kevincantu** [comment]
I used the Finder.

**Comment by monde** [comment]
Noted the work around is to use curl as downloads via browser (Chrome et. al.) encumber the archive with additional OSX security sandbox restrictions.
