### ISSUE TITLE
[2.1.0 -> 2.1.1 Problem] `okta-aws-cli` runs twice and not working.

### ISSUE THREAD

**Issue by devkoriel** [okta/okta-aws-cli#192]
As aforementioned in the title, after updating `okta-aws-cli` from 2.1.0 to 2.1.1, it's not working. The symptoms are two.

1. `okta-aws-cli` runs twice even after once the authentication's done successfully.
2. In the second running, `Error: open : no such file or directory` is occurring. No other clues provided with the `--debug` option.

The only change I've checked between the versions is below

https://github.com/okta/okta-aws-cli/compare/v2.1.0...v2.1.1#diff-54c7c1af5fa8d5db4dc49f0e8e80e93ba2b1183ba4d5c9e2e5729e6deae6a3cdR373-R435

**Comment by shanesmith** [comment]
I've experienced similar issues, plus `okta-aws-cli` prompts for a role despite passing one to the command.

```sh
$ env | grep OKTA
OKTA_AWSCLI_FORMAT=aws-credentials
OKTA_AWSCLI_IAM_IDP=arn:aws:iam::12345:saml-provider/Okta
OKTA_AWSCLI_OPEN_BROWSER=true
OKTA_AWSCLI_SESSION_DURATION=43200
OKTA_AWSCLI_WRITE_AWS_CREDENTIALS=true
OKTA_AWSCLI_EXPIRY_AWS_VARIABLES=true
OKTA_AWSCLI_ORG_DOMAIN=clio.okta.com
OKTA_AWSCLI_OIDC_CLIENT_ID=abc123
OKTA_AWSCLI_ACCOUNT_FEDERATION_APP_ID=abc123

$ okta-aws-cli --aws-iam-role arn:aws:iam::12345:role/Foo --profile Foo

Web browser will open the following URL to begin Okta device authorization for the AWS CLI

https://clio.okta.com/activate?user_code=ABC123

IdP: arn:aws:iam::12345:saml-provider/Okta
? Choose a Role:  [Use arrows to move, type to filter]
arn:aws:iam::12345:role/Foo
arn:aws:iam::12345:role/Bar
> arn:aws:iam::12345:role/Xyzzy
```

**Comment by monde** [comment]
I'll get this addressed asap today.

**Comment by MatthewJohn** [comment]
Hey all,

I'm very sorry about this issue - I've proposed a fix in https://github.com/okta/okta-aws-cli/pull/196

From my testing of these two use cases, it seems to resolve the issue and @shanesmith has been able to confirm

Thanks
Matt
