### ISSUE TITLE
Include account name in IDP prompt

### ISSUE THREAD

**Issue by rjpipino** [okta/okta-aws-cli#202]
Having the name of the account would be helpful in the IDP prompt. Something like

```
? Choose an IdP:  [Use arrows to move, type to filter]
> AccountName1 - arn:aws:iam::<account-number-1>:saml-provider/CFA-OKTA-PROD
 AccountName2  -arn:aws:iam::<account-number-2>:saml-provider/CFA-OKTA-PROD
 AccountName3 - arn:aws:iam::<account-number-3>:saml-provider/CFA-OKTA-PROD
```

**Comment by monde** [comment]
@rjpipino let me know if [Friendly IdP and Role menu labels](https://github.com/okta/okta-aws-cli?tab=readme-ov-file#friendly-idp-and-role-menu-labels) is the feature you looking for.

**Comment by rjpipino** [comment]
@monde Yes! That would do that, thanks!
