### ISSUE TITLE
Failure to parse config yaml should cause default exit

### ISSUE THREAD

**Issue by ProsaicWildfire** [okta/okta-aws-cli#208]
As it stands, it seems that a malformed configuration yaml can cause confusing errors (asking for arg values that seem to be provided in the config file), requiring the debug option to be used to determine the root cause of the error. I think a case where the config file exists but is malformed should cause an immediate, visible error and a halt of execution.

**Comment by monde** [comment]
I'll have it print out warning.

```
 $ okta-aws-cli web ...
WARNING: issue with okta.yaml file: yaml: line 6: did not find expected key
? Choose an IdP:  [Use arrows to move, type to filter]
> ABC
```
