### ISSUE TITLE
Add option to skip everything if the AWS session hasn't expired

### ISSUE THREAD

**Issue by EliseAv** [okta/okta-aws-cli#211]
Scenario:

```
$ okta-aws-cli web -p account0
Web browser will open the following URL to begin Okta device authorization for the AWS CLI

https://aaaaa.oktapreview.com/activate?user_code=........

  IdP: AWS Account 0
  Role: arn:aws:iam::000000000000:role/MyRole
Updated profile "account0" in credentials file "~/.aws/credentials".
$ okta-aws-cli web -p account0
  IdP: AWS Account 0
  Role: arn:aws:iam::000000000000:role/MyRole
Updated profile "account0" in credentials file "~/.aws/credentials".
```

The session is refreshed without need. I get that it might be close to expiration, and a refresh is still useful in that sense.

But we have a lot of scripts that are done in <10s (they were built for saml2aws which has that feature) and I don't want to keep refreshing my sessions for them. The `--expiry-aws-variables` option is useful for that purpose... but writing a bash script that finds the correct profile and parses its expiration string for comparison is ridiculously complicated. I'd like some simpler option in the spirit of `--skip if still good for = 10 seconds` or even just if still good for now, since retrying is usually cheap.

**Comment by monde** [comment]
This exists as `--cache-access-token` https://github.com/okta/okta-aws-cli?tab=readme-ov-file#global-settings

**Comment by EliseAv** [comment]
No, `--cache-access-token` is a different functionality. It will still re-issue my AWS credentials without re-asking for credentials.

What's needed is a fully idempotent mode that will not modify `~/.aws/credentials` at all.

**Comment by Meroje** [comment]
@monde having the token exchange happen everytime is really slowing down operations, can this issue be revisited ?
