### ISSUE TITLE
`OKTA_AWSCLI_PROFILE` not taken into account

### ISSUE THREAD

**Issue by QuentinBtd** [okta/okta-aws-cli#216]
Hello,

With okta-aws-cli v2.2.0, the env var `OKTA_AWSCLI_PROFILE` is not taken into account. 

The `default` profile is updated instead of the profile set with the variable.

Tested on MacOS and Ubuntu.

**Comment by monde** [comment]
I see the flaw, this will be fixed in the next release going out this week.
