### ISSUE TITLE
New error thrown for ".okta/okta.yaml" not found

### ISSUE THREAD

**Issue by estokes-vs** [okta/okta-aws-cli#226]
I've upgraded today from okta-aws-cli 2.1.2 -> 2.3.0 and there appears to be a new error that is being thrown that likely could be resolved by the program itself. 

The command we use to authenticate is below:
```
okta-aws-cli --org-domain <DOMAIN> --oidc-client-id <CLIENT_ID> --aws-acct-fed-app-id <AWS_ACCT_FED_APP_ID> --format aws-credentials --open-browser --write-aws-credentials --session-duration <DURATION> --cache-access-token --expiry-aws-variables
```

And the new error is:
```
WARNING: issue with okta.yaml file. Run `okta-aws-cli debug` command for additional diagnosis.
Error: open /Users/<USERNAME>/.okta/okta.yaml: no such file or directory
```

I verified that this pops up each time we run the command but never is resolved automatically by the system, but it feels like it could be.  Can the `okta-aws-cli` just create this folder and file if it doesn't exist, or emit an error if it's unable to create the items due to local permissions?

**Comment by rmadoori754** [comment]
I have same issue

**Comment by monde** [comment]
I will clean this up ...

**Comment by monde** [comment]
#232
