### ISSUE TITLE
AWS credential file output just appends

### ISSUE THREAD

**Issue by ctennis** [okta/okta-aws-cli#23]
If you already have creds from the same profile in the file, they don't get replaced - the file is append only.

If you have more than one profile of the same name in the file, aws tools just error as opposed to using the latest one.

Suggest we update this code. The saml2aws equivalent is MIT licensed and works great, and has a bunch of edge use case stuff in it that has accumulated over the past 6 years. Suggest we use that as a basis and replace the current code.

**Comment by nickgamb** [comment]
We are intentionally looking to avoid use of the credentials file or any other local storage of credentials. The goal is to keep all credentials in memory.

**Comment by ctennis** [comment]
I understand the motivation but that won’t work with dozens of tools downstream. We’re not in a position to have to reauth with Okta every time we make an aws call, given that the flow requires the browser in the middle. 

credentials file is a necessary evil

**Comment by MikeMondragon-okta** [comment]
Closed by #30 , CLI flag `--write-aws-credentials`
