### ISSUE TITLE
When I provide the `--aws-iam-idp` option, I still need to select an IdP in the cli

### ISSUE THREAD

**Issue by reakaleek** [okta/okta-aws-cli#230]
When I provide the `--aws-iam-idp` option, I still need to select an IdP in the cli. But when I provide the `--aws-iam-role` option, the role is selected automatically.

```bash
okta-aws-cli web \
  --org-domain=<redacted> \
  --oidc-client-id=<redacted> \
  --open-browser \
  --cache-access-token \
  --aws-iam-idp=arn:aws:iam::<redacted>:saml-provider/Okta \
  --aws-iam-role=arn:aws:iam::<redacted>:role/okta-dev
? Choose an IdP:  [Use arrows to move, type to filter]
  IdP A
> IdP B
  IdP C
  ```
  
Is this a bug or is this the expected behaviour?

**Comment by reakaleek** [comment]
Oh. Duplicate of https://github.com/okta/okta-aws-cli/issues/228

**Comment by reakaleek** [comment]
I was able to preselect the IdP using the App ID, with the option:

`--aws-acct-fed-app-id=<redacted>`

**Comment by kevinschaul** [comment]
My colleagues upgraded from v2.1.0 to v2.4.1 and ran into this error. Further I tried specifying the idp in an okta.yaml file but the same issue happens -- the cli prompts me to select the idp. I am also unsure how to downgrade (See #195). Any suggestions for how to proceed? Thanks!
