### ISSUE TITLE
Support configuring sts endpoint

### ISSUE THREAD

**Issue by kimxogus** [okta/okta-aws-cli#236]
Today, we had a problem using okta-aws-cli because AWS had a [global sts endpoint issue](https://health.console.aws.amazon.com/health/home?region=us-east-1#/event-log?eventID=arn:aws:health:global::event/IAM/AWS_IAM_OPERATIONAL_ISSUE/AWS_IAM_OPERATIONAL_ISSUE_C9750_3CF4B9D9C39&eventTab=details). We couldn't connect to the global `sts.amazonaws.com` endpoint, and our regional endpoint was ok.
Therefore we tried to use regional sts endpoint for okta-aws-cli as a workaround, but we couldn't find a configuration to change sts endpoint address to a regional endpoint.
It would be very helpful if okta-aws-cli provides a configuration to change sts endpoint address.

**Comment by monde** [comment]
Good feedback, thank you @kimxogus

**Comment by monde** [comment]
@kimxogus I was looking at the golang sdk for aws/sts and it allows setting the AWS region on the sdk client when we initialize it. And we do that https://github.com/okta/okta-aws-cli/blob/master/internal/webssoauth/webssoauth.go#L362 if aws region has been set on okta-aws-cli

Can you try adding the CLI flag `--aws-region` (see [global config section](https://github.com/okta/okta-aws-cli?tab=readme-ov-file#global-settings)) and see if that setting gets you what you are looking for? e.g.

`okta-aws-cli web --oidc-client-id 0oabc --aws-acct-fed-app-id 0oaxy --org-domain my-org.okta.com --aws-region us-west-2`


For example, if I try to run in a gov cloud region I can see the sdk client is formatting the STS host correctly:

```
okta-aws-cli web \
  --oidc-client-id 0oabc \
  --aws-acct-fed-app-id 0oaxy \
  --org-domain my-org.okta.com \
  --aws-region us-gov-east-1 \
  --debug-api-calls
```

```
...
? Choose a Role: arn:aws:iam::123:role/test
2024/09/03 10:17:57 [DEBUG]  API Request Details:
---[ REQUEST ]---------------------------------------
POST / HTTP/1.1
Host: sts.us-gov-east-1.amazonaws.com
...
```

Also, the aws golang sdk client respects the standard AWS environment variables like `AWS_REGION` so this also works
`AWS_REGION=us-example-7 okta-aws-cli ...`

```
...
-----------------------------------------------------
2024/09/03 10:25:26 [DEBUG]  API Request Details:
---[ REQUEST ]---------------------------------------
POST / HTTP/1.1
Host: sts.us-example-7.amazonaws.com
Content-Length: 12903
Content-Type: application/x-www-form-urlencoded; charset=utf-8
User-Agent: aws-sdk-go/1.44.94 (go1.22.4; darwin; arm64)
...
-----------------------------------------------------
Error: STS Assume Role With SAML API error; given idp:
caused by: Post "https://sts.us-example-7.amazonaws.com/": dial tcp: lookup sts.us-example-7.amazonaws.com: no such host
...
```
