### ISSUE TITLE
Auth fails if 2FA requirement is in place for federated app

### ISSUE THREAD

**Issue by ctennis** [okta/okta-aws-cli#31]
I opened this ticket with Okta support (01589890) but they said to open a github issue here. I don't believe this is specific to this utility moreso specific to something on the backend related to the federated app, but nonetheless, putting it here...

When attempting to use the login flow of the okta-aws-cli app, we get an error:

Error: fetching SSO web token received API response "400 Bad Request"

I've added debugging output to get the additional error:

{"error":"invalid_grant","error_description":"The application's assurance requirements are not met by the 'subject_token'."}

The request body has a subject_token of:

{
  "sub": "xxx",
  "ver": 1,
  "iss": "ouroktaurl",
  "aud": "yyy",
  "iat": 1670864573,
  "exp": 1670868173,
  "jti": "zzz",
  "amr": [
    "otp",
    "mfa",
    "hwk",
    "user",
    "pwd"
  ],
  "idp": "qqq",
  "sid": "idxn78aJdyrQtiGdUCnYwTMdw",
  "auth_time": 1670862872,
  "at_hash": "pJcnUxGzD2iYj5l2jJdeqQ"
}

and an actor_token of:

{
  "ver": 1,
  "jti": "xxx",
  "iss": "https://myurl",
  "aud": "https://myurl",
  "sub": "myemail",
  "iat": 1670864573,
  "exp": 1670868173,
  "cid": "clientid",
  "uid": "userid",
  "scp": [
    "openid",
    "okta.apps.sso"
  ],
  "auth_time": 1670862872
}

The application actually had a auth policy that required MFA on each login. This seems to be what was breaking. I changed the auth policy to any two factors, and this fixed the issue. However, we'd like to understand if there's a possibility of using the required MFA on each login here. It feels like this is a bug on the Okta side that it would break silently (see screenshot). Note that logging in with the okta chiclet to the federated app works fine.

Note that when I use an incognito window to login (as opposed to an already existing open browser session), it succeeds when doing the device auth flow with okta-aws-cli

So - is there a trick here to be done where we can retain the 2FA requirement on the federated app?

**Comment by monde** [comment]
That seems like expected behavior to me - if the AWS Federation App has more strict security requirements than the OIDC native app - you probably shouldn't be able to get a web sso token. I'll ping customer support and see if they can get more information from the team that owns that part of the Okta service.

**Comment by ctennis** [comment]
Yep, totally agree - it's just the error was difficult to diagnose. This device token exchange flow doesn't look to be documented anywhere in the normal Okta docs yet, so trying to deduce what *The application's assurance requirements are not met by the 'subject_token'.* means took some time. In our case, I added the OIDC app per the instructions but it got put into a default app auth group different than the federated one.

**Comment by monde** [comment]
We carved out recommendations section in the readme with this feedback @ctennis https://github.com/okta/okta-aws-cli#recommendations
Thanks for all your help and contributions.
