### ISSUE TITLE
Create a Homebrew formulae

### ISSUE THREAD

**Issue by tim-fitzgerald** [okta/okta-aws-cli#35]
Hey folks, would love if we could get this tool rolled out via `brew`. Are there any plans to [create a homebrew](https://docs.brew.sh/Adding-Software-to-Homebrew) formulae for this?

**Comment by monde** [comment]
Hey @tim-fitzgerald we have plans to do this, agreed, it will make it convenient for the osx brew folks.

**Comment by tim-fitzgerald** [comment]
Realised there is no auto update for this tool yet, and this issue would also resolve that issue. Just highlighting that as another win if this gets actioned.

**Comment by tim-fitzgerald** [comment]
Any update or movement on this? Id consider this fairly critical for any serious deployment of this tool so would be greatly appreciated if we could see some movement on it

**Comment by monde** [comment]
@tim-fitzgerald Okta legal is looking at this to see if they agree with brew as a distribution channel. My colleague @duytiennguyen-okta has the resequent brew ruby code working in his development environment and we are just waiting on sign off.

**Comment by reegnz** [comment]
@monde I mean, it's licensed as Apache, is open-sourced, has downloadable github releases so I think anyone can create a formula for this and contribute to https://github.com/Homebrew/homebrew-core , Okta's legal obligation ended where you released it under the Apache license. ;)

**Comment by monde** [comment]
@reegnz Okta legal had to decide if they were ok with brew as a distribution channel _that we are going to support_. Their review didn't have anything to do with licensing.

fwiw, we've been cleared for supporting brew distribution. My colleague @duytiennguyen-okta is workin on this.

**Comment by duytiennguyen-okta** [comment]
Okta-aws-cli is now on homebrew
