### ISSUE TITLE
Rename `internal` package to `pkg`

### ISSUE THREAD

**Issue by TwiN** [okta/okta-aws-cli#57]
Thinking about having our internal CLI move from saml2aws to okta-aws-cli, but everything we'd need from `okta-aws-cli` is hidden in the `internal` package.

Would it be possible to rename the `internal` package to `pkg` so that the internal functions, variables and types can be exported?

I don't mind making a PR for it myself.

**Comment by monde** [comment]
Thanks @TwiN I'll discuss this with our PM @jefftaylor-okta

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-573114

**Comment by TwiN** [comment]
@monde I've created a PR to resolved this, if your team decides to accept the feature request: #64
