### ISSUE TITLE
Write x_security_token_expires in credential file

### ISSUE THREAD

**Issue by JohnPaton** [okta/okta-aws-cli#63]
`saml2aws` writes an additional entry `x_security_token_expires` in the credentials file, presumably calculated based on the session duration provided when requesting authentication. This allows tools like [starship](https://github.com/starship/starship) to quickly check if credentials are still valid without making any calls to AWS. It would be nice to get this from `okta-aws-cli` as well.

**Comment by JohnPaton** [comment]
Ah I see this would be closed by #56

**Comment by monde** [comment]
Just double checking @JohnPaton this is feature parity with `saml2aws` for your use case?

**Comment by JohnPaton** [comment]
Yes, this is the same functionality that `saml2aws` provides

**Comment by monde** [comment]
Making note, we are actively discussing on PR #56

**Comment by monde** [comment]
Addressed in #56 and #99
