### ISSUE TITLE
Chocolatey package for Windows

### ISSUE THREAD

**Issue by curator** [okta/okta-aws-cli#83]
Hi all, for Windows parity (and a significant chunk of our user base), a Windows package would be awesome.  For us this would commonly be chocolatey, but there may be others in common use.

**Comment by monde** [comment]
This is under active discussion in our team.

**Comment by mieliespoor** [comment]
Before chocolatey, winget should be the first target of support.

**Comment by monde** [comment]
We're official with Chocolatey now! 🎉 
https://community.chocolatey.org/packages/okta-aws-cli
