### ISSUE TITLE
Garbage printed when using xdg-open

### ISSUE THREAD

**Issue by perj** [okta/okta-aws-cli#91]
On Linux, when using `eval $(okta-aws-cli -b)`, I assume -b flag makes the tool exec `xdg-open`. Unfortunately, the output of that command is piped to stdout and become part of the string passed to `eval`.

For example, on my laptop it prints
```
Öppnas i en befintlig webbläsarsession.
```
which causes the error
```
Öppnas: command not found
```

The string is printed asynchronously, after xdg-open exits. Presumably it's piped from Chrome somehow, based on the output.

**Comment by monde** [comment]
Seems to be coming from Brave.
https://fossies.org/linux/brave-core/app/resources/generated_resources_sv.xtb

Unfortunately, we can't control what 3rd party tools print to STDOUT when capturing the STDOUT from `okta-aws-cli` with an eval. I'm not certain to xde-open alternatives. However, we are using pkg/browser for popping the browser and I found this comment on the linux driver:
https://github.com/pkg/browser/blob/99a9298f083b488debce97664d7d7530fe6d5c79/browser_linux.go#L11-L13
```
https://github.com/pkg/browser/blob/99a9298f083b488debce97664d7d7530fe6d5c79/browser_linux.go#L11-L13

```

**Comment by perj** [comment]
It's possible to set where the stdout of the command goes here: https://github.com/pkg/browser/blob/master/browser.go#L16

**Comment by monde** [comment]
@perj I'll slip this in on the next release, nice find.
